import type { Metadata } from "next";
import { Inter, Exo_2 } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import AVES_Logo from "./assets/2021-avesfrance-court-noir-avatar.jpg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prefectures scanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <div className="flex p-4 shadow-sm shrink-0 items-center justify-between">
            <Image alt="logo" src={AVES_Logo} height={50} width={50} />
            <h1 className="font-bold text-2xl/5 tracking-wide uppercase text-violet-950">
              Scanner de consultations publiques
            </h1>
            <div></div>
          </div>
          <main className="grow bg-violet-50 flex justify-center py-5">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
