import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import AVES_Logo from "./assets/2021-avesfrance-court-noir-avatar.jpg";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prefectures scanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col">
          <div className="flex shrink-0 items-center justify-between p-4 shadow-sm">
            <Link href="/">
              <Image alt="logo" src={AVES_Logo} height={50} width={50} />
            </Link>
            <h1 className="text-2xl/5 font-bold uppercase tracking-wide text-violet-950">
              Scanner de consultations publiques
            </h1>
            <div></div>
          </div>
          <main className="flex grow justify-center bg-violet-50 py-5">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
