import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prefectures scanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <div className="flex justify-center py-5 shadow-sm shrink-0">
            <h1 className="font-bold text-2xl text-violet-950">
              PREFECTURES SCANNER
            </h1>
          </div>
          <div className="grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
